name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: Checkout code
            uses: actions/checkout@v2
            
          - name: Install dependencies
            run: npm install

          - name: Build app
            run: npx nx build --verbose

          - name: Run unit tests
            run: npx nx test