name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npx nx run-many --target=build --all --verbose

      - name: Run unit tests
        run: npx nx run-many --target=test --all --verbose
