name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Verify npx is working
        run: npx --version

      - name: Verify npm packages
        run: npm ls

      - name: Delete node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json

      - name: Intentando con serve
        run: npx nx serve

      - name: Build app
        run: npx nx build --verbose

      - name: Run unit tests
        run: npx nx test