name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Delete node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies using npm ci
        run: npm ci

      - name: Verify nx installation
        run: npm ls nx

      - name: Build app
        run: npx nx build --verbose

      - name: Run unit tests
        run: npx nx test