name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: rm -rf node_modules package-lock.json
            npm install
            npm ci
            nx reset

      - name: Verify Nx installation
        run: nx --version

      - name: RUn graph
        run: nx graph --verbose

      - name: Nx Report
        run: nx report

      - name: Try test only
        run: npx nx run-many --target=test --all

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Build and test affected
        run: npx nx affected -t build test
